/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Issue 3712 - Angular required+nullable query params
 * OpenAPI spec version: 1.0.0
 */
import { httpResource } from '@angular/common/http';
import type {
  HttpResourceOptions,
  HttpResourceRef,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

import type { ListThingsParams } from './model';

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>;

type AngularHttpParamValue =
  | string
  | number
  | boolean
  | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function listThingsResource(
  params: Signal<ListThingsParams> | undefined,
  options: OrvalHttpResourceOptions<string[], unknown> & {
    defaultValue: NoInfer<string[]>;
  },
): HttpResourceRef<string[]>;
export function listThingsResource(
  params?: Signal<ListThingsParams>,
  options?: OrvalHttpResourceOptions<string[], unknown>,
): HttpResourceRef<string[] | undefined>;
export function listThingsResource(
  params?: Signal<ListThingsParams>,
  options?: OrvalHttpResourceOptions<string[], unknown>,
): HttpResourceRef<string[] | undefined> {
  return httpResource<string[]>(() => {
    const request = {
      url: `/things`,
      params: filterParams(params?.() ?? {}, new Set<string>(['cursor'])),
    };
    return request;
  }, options);
}

export type ListThingsResourceResult = NonNullable<string[]>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
